### ISSUE TITLE
🐛 Wallet download page suggesting wrong version

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vega.xyz#192]
Wallet download bug that Michael raised on slack

Wallet download page suggested I download the AMD wallet on my M1 machine

https://vega.xyz/wallet/ defects what system you are on and gives you a primary download button based on your machine but I think it is suggesting the wrong version for my Mac (an M1).. it suggests https://github.com/vegaprotocol/vegawallet-desktop/releases/download/v0.1.1/vegawallet-desktop-darwin-amd64.zip I think M1 is ARM

[@Penny Andrews](https://app.asana.com/0/1200954103385872/board)5 Jul
It seems like it is downloading the AMD one when you download from Safari
You correctly get the ARM one when downloading from Chrome

**Comment by goslingo** [comment]
After some research, it seems that there is no reliable method for detecting what CPU architecture a user is using, particularly when on a Mac.

Therefore I have simplified this page so that it doesn't try and suggest a particular binary, instead just presenting a drop down menu with all the options.

https://deploy-preview-261--vega.netlify.app/wallet/

**Comment by pennyandrews** [comment]
Looks good to me @goslingo !
